#ifndef DFTRACER_UTILS_ANALYZERS_PIPELINE_PIPELINE_H
#define DFTRACER_UTILS_ANALYZERS_PIPELINE_PIPELINE_H

#include <dftracer/utils/analyzers/trace.h>

#endif  // DFTRACER_UTILS_ANALYZERS_PIPELINE_PIPELINE_H
